.PHONY: clean All

All:
	@echo "----------Building project:[ codelite-wxwidgets4 - Debug ]----------"
	@cd "codelite-wxwidgets4" && "$(MAKE)" -f  "codelite-wxwidgets4.mk"
clean:
	@echo "----------Cleaning project:[ codelite-wxwidgets4 - Debug ]----------"
	@cd "codelite-wxwidgets4" && "$(MAKE)" -f  "codelite-wxwidgets4.mk" clean
