//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _DRIVER_CODELITE_WXWIDGETS4_WXCRAFTER_BASE_CLASSES_H
#define _DRIVER_CODELITE_WXWIDGETS4_WXCRAFTER_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/splitter.h>
#include <wx/panel.h>
#include <wx/glcanvas.h>
#include <wx/propgrid/manager.h>
#include <wx/propgrid/property.h>
#include <wx/propgrid/advprops.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class MainFrameBaseClass : public wxFrame {
protected:
  wxSplitterWindow *m_splitter15;
  wxPanel *m_splitterPage19;
  wxGLCanvas *m_glCanvas33;
  wxPanel *m_splitterPage23;
  wxPropertyGridManager *m_pgMgr27;
  wxPGProperty *m_pgProp29;
  wxPGProperty *m_pgProp35;
  wxPGProperty *m_pgProp37;
  wxPGProperty *m_pgProp39;
  wxPGProperty *m_pgProp41;

protected:
  virtual void onGlLeftUp(wxMouseEvent &event) { event.Skip(); }

public:
  wxGLCanvas *GetGlCanvas33() { return m_glCanvas33; }
  wxPanel *GetSplitterPage19() { return m_splitterPage19; }
  wxPropertyGridManager *GetPgMgr27() { return m_pgMgr27; }
  wxPanel *GetSplitterPage23() { return m_splitterPage23; }
  wxSplitterWindow *GetSplitter15() { return m_splitter15; }
  MainFrameBaseClass(wxWindow *parent, wxWindowID id = wxID_ANY,
                     const wxString &title = _("My Frame"),
                     const wxPoint &pos = wxDefaultPosition,
                     const wxSize &size = wxSize(500, 300),
                     long style = wxDEFAULT_FRAME_STYLE | wxCAPTION |
                                  wxRESIZE_BORDER | wxMAXIMIZE_BOX |
                                  wxMINIMIZE_BOX | wxSYSTEM_MENU | wxCLOSE_BOX |
                                  wxFULL_REPAINT_ON_RESIZE);
  virtual ~MainFrameBaseClass();
};

#endif
